### ISSUE TITLE
CellInput - Unable to set initial value

### ISSUE THREAD

**Issue by ghost** [lodev09/react-native-cell-components#5] opened 2017-10-02 18:41 UTC
While CellInput does use TextInput within it, I am unable to set an initial value.

I'm assuming it is done like so; <CellInput title="Hello" icon="label" value={this.state.someValue} />

In addition, I have some DatePickers on the same page. When I set the CellInput's onChangeText={(v) => {this.setState({someValue: v}) I get the following error; nextProps.date.getTime is not a function. 
I'm not sure how the CellInput change is triggering the DatePicker.

**Comment by ghost** [comment] 2017-10-02 19:16
I was able to get by the Datepicker issue by changing the componentWillReceiveProps to use nextProps.date.valueOf() in stead of getTime().  Not sure why getTime doesn't work, though.

**Comment by lodev09** [comment] 2017-10-15 01:40
I think the issue is that you didn't set your initial state with a `date` value. See example for reference. I'm closing this for now, re-open if you experience any further issue.

**Closed as completed by lodev09** 2017-10-15 01:40 UTC
